version: '3.3'

services:
  mysql:
    image: mysql:8
    command: --lower_case_table_names=2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RECIPES
    ports:
      - "3306:3306"
    volumes:
      - ../assessment/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  api:
    build: ../assessment/.
    image: abn-amro/assessment-api
    hostname: abn-amro-assessment-api
    container_name: abn-amro-assessment-api
    links:
      - mysql # waits for mysql
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=container" # Using profile container, to connect with mysql

  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    links:
      - api # waits for api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
